version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      time: "03:00"
      timezone: UTC

  - package-ecosystem: cargo
    directory: /
    schedule:
      interval: weekly
      time: "03:30"
      timezone: UTC
