name: Display checks that are run by Cargo
description: Convert the output of cargo check (and more) to the GitHub Actions comment format
author: \@georglauterbach and \@olix0r

branding:
  color: white
  icon: check-circle

inputs:
  version:
    description: The version of cargo-action-fmt to use
    required: false
    default: v0.1.2

runs:
  using: composite
  steps:
    - name: Install cargo-action-fmt
      id: install
      shell: bash
      run: |
        set -eE -u -o pipefail
        shopt -s inherit_errexit

        curl --proto '=https' --tlsv1.3 -sSfL "https://github.com/georglauterbach/cargo-action-fmt/releases/download/v${{ inputs.version }}/cargo-action-fmt-$(uname -m)-unknown-linux-musl.tar.gz" | tar xz - -C /usr/local/bin/
