name: Setup cargo-action-fmt
description: Convert the output of cargo check (and more) to the GitHub Actions comment format
author: \@georglauterbach and \@olix0r

runs:
  using: composite
  steps:
    - name: Install cargo-action-fmt
      id: install
      shell: bash
      run: |
        set -eE -u -o pipefail
        shopt -s inherit_errexit

        curl --proto '=https' --tlsv1.3 -sSfL "https://github.com/georglauterbach/cargo-action-fmt/releases/download/release/v0.1.0/cargo-action-fmt-v0.1.0-$(uname -m)-unknown-linux-musl.tar.gz" | tar zvxf - -C /usr/local/bin/ cargo-action-fmt
